### PR TITLE
feat: add wallet selector

### LINKED ISSUE #209: Implement EVM wallet selector in Prompt Wars NavBar
The current NEAR wallet selector should be replaced by either a custom EVM wallet selector or one that's already  built. 

## BEFORE IMPLEMENTING

Please write down your plan for this. What packages are you planning to install. What selector, etc.
The design must follow the current guidelines and styles. 

Users must be able to connect any EVM compatible wallet extension (and/or) enter from a dApp browser, eg. Binance dApp Web3 wallet, or Metamask android app. 

**The selector must allow selecting different chains, eg. Ethereum, Optimisim, Arbitrum, etc...**

**The selector must show the current chain network, eg. Binance opChain testnet**

## How to get paid

A working implementation of the EVM compatible wallet selector. User should be able to sign any transaction inside the game dApp by using the selected wallet. 

The wallet MUST show the user's balance in the native coin of the selected chain AND the collateral token balance of the game.

### Submit a Pull Request

Maintainers will pull your changes before merging and test everything is working as expected. Note that other devs may work in this issue too. Quality is key.

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: https://github.com/aufacicenta/pulsemarkets/issues/209

1) what are guest wallets ? how to connect guest wallets here?

Demo

Screenshot 2023-11-19 at 6 35 04 PM

Screenshot 2023-11-19 at 6 35 19 PM

Screenshot 2023-11-19 at 6 35 35 PM

Packages Added:- @web3modal/wagmi, wagmi and viem

Environment Variable added

NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID

Create a project on https://cloud.walletconnect.com and copy the project id

### CODE REVIEW

**Comment by netpoe** [comment]
@Udit-takkar wagmi and this package looks good.
I'll make some updates to your code and I'll merge it.

**Comment by Udit-takkar** [comment]
> @Udit-takkar wagmi and this package looks good. I'll make some updates to your code and I'll merge it.

Okay

**Comment by netpoe** [comment]
@Udit-takkar please allow @netpoe to push to your forked repo so that my changes reflect in your PRs 🙏

**Review by netpoe — CHANGES_REQUESTED** [review]
@Udit-takkar I added a context controller to follow the conventions of our codebase. 

The WalletConnect selector works well, I moved it out of Web3Modal and put it inside the `EVMWalletSelectorContextController`. 

To merge this PR please:

- Add the new selector to `WalletSelectorMobile`
- Remove `<WalletStateContextController>` and `<NearWalletSelectorContextController>` from `DashboardLayout` to forget about NEAR and leave the ground clear for implementing the new Solidity contract interfaces

**Comment by Udit-takkar** [comment]
@netpoe i am getting some errors after pulling your changes.

Screenshot 2023-11-26 at 1 55 24 AM


ah, yes! forgot about that.
There's a sequelize provider that requires this package.
You need to:

```
cd database/
touch .env
sh install.sh

cd app/
yarn link "@aufacicenta/fileagent-db"
```

**Comment by Udit-takkar** [comment]
@netpoe should i also remove NearMarketContractContextController  and NearPromptWarsMarketContractContextController (and related files useNearPromptWarsMarketContractContext ?

These file uses useWalletStateContext(). what does walletState.context.connection and walletState.context.wallet represent? we would have to replace it with something from wagmi hooks and remove @near-wallet-selector too.

**Comment by netpoe** [comment]
> @netpoe should i also remove NearMarketContractContextController and NearPromptWarsMarketContractContextController (and related files useNearPromptWarsMarketContractContext ?
> 
> These file uses useWalletStateContext(). what does walletState.context.connection and walletState.context.wallet represent? we would have to replace it with something from wagmi hooks and remove @near-wallet-selector too.

Yeah... This is an interesting problem. We don't want to break the game functionality but we don't want to turn this PR into a huge refactor.

What's your take in this one? Should we merge this one and start a new PR that removes all NEAR functionality? This would be better no?

The EVM Wallet Selector works fine already. Let's merge and start a new PR to remove all NEAR features and implement the Solidity features.

**Comment by netpoe** [comment]
@Udit-takkar paid!
Let's start a new PR branching out from ´aufacienta:EVM´ to move away from NEAR and integrate the new Solidity ABI.

**Comment by Udit-takkar** [comment]
@netpoe ok

**Pull request merged**
